apiVersion: v1
kind: Secret
metadata:
  name: cookbookbo-front
data:
  GOOGLE_ID: Z29vZ2xlX2lkX29hdXRo
  GOOGLE_SECRET: Z29vZ2xlX3NlY3JldF9vYXV0aA==
  NEXT_PUBLIC_API_URL: aHR0cDovL2xvY2FsaG9zdDo4MDAwL2FwaQ==
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: aHR0cDovL2xvY2FsaG9zdDo4MDAwL2FwaQ==
  SECRET: c3VwZXJfc2VjcmV0X2dlbmVyYXRvcg==
